### PR TITLE
Port to TelepathyGLib

### PR DESCRIPTION
**Pull request by Aniket21mathur**
@quozl  @pro-panda @chimosky please review. Thanks!

### CODE REVIEW

**Comment by quozl** [comment]
Please test before commit, thanks.

**Comment by Aniket21mathur** [comment]
Tested activity before telepathy port, it seems that the collaboration for activity is already broken. See #15 . Thanks!

**Comment by quozl** [comment]
It was your use of _get_shared_activity_ function without calling it that told me it wasn't tested. :grin:

**Comment by Aniket21mathur** [comment]
Thanks :sweat_smile: ,didn't noticed that. I will wait until #15 is fixed.

**Comment by quozl** [comment]
Thanks.  Reviewed. Deja vu.

* [ ] you've done flake8 changes mixed with other changes; this make reviewing much harder, please try to do these in a different pull request next time,
* [ ] when wrapping argument lists, please do it intelligently, allowing more than one argument per line, as the style you've chosen unnecessarily consumes lines, (limits comprehension of source code when a new developer reads the code in an editor).
* [ ] you've not finished flake8 changes; `python2 -m flake8 .` still gives three hits,
* [ ] commit message has typo,
* [ ] missing end of line mark on `.flake8` file.

Suggestions for workflow;
* use flake8 before commit,
* review every change, because somebody else will, e.g. use interactive `git add`, or a tool that calls it, (my choice is magit in emacs, but you may have other choices),
* discard changes you don't want to make,
* take great care with automatic formatters.

**Comment by Aniket21mathur** [comment]
Thanks, will surely take care from next pr, I removed flake8 commits as I will open a separate pr for flake8. :sweat_smile: .

**Comment by quozl** [comment]
Ok, thanks.

**Pull request merged**
