### PR TITLE
Sugar3.speech

### PR DESCRIPTION
**Pull request by chimosky**

### CODE REVIEW

**Comment by chimosky** [comment]
@quozl in addressing some of your comments

> - [x] there was no download progress, which Get Books and Get IA Books do have,


When I tried downloading a book, the download progress showed at the top of the activity canvas.

> - [x] adjusting the pitch during speaking stops the speaking, and it could not be restarted.

Fixed in 323df44

> - [ ] "the books button above" ... I didn't know which button this was, as there was no tooltip ... the instructions could contain an image of the button,

I'll add the image to the instructions as setting a tooltip makes the button not work as intended.

> - [ ] the instructions that begin "Outside of a dog" are too small to read; they are in a font smaller than the minimum Sugar font size,

We talked about this, do you intend I leave it that way as the author created the activity for OLPC devices or I should increase the font-size.

> - [ ] "download button" actually has a tooltip of "Get Book", and the icon is not our standard download icon as used in Browse,

The `download button` icon as used in Browse is great, I'll look at using that as it entails removing the current download progress as the icon takes care of that.

**Comment by quozl** [comment]
Thanks.

**Comment by chimosky** [comment]
@quozl for my last two replies, what do you suggest?

**Comment by quozl** [comment]
Perhaps the font size is a platform issue.  Does it look readable to you?

**Comment by chimosky** [comment]
> Perhaps the font size is a platform issue. Does it look readable to you?

Although the font size is small but it's readable to me and it would be great if it was a bit bigger.

**Pull request merged**
